#!/usr/bin/env python3
"""Generate js/cars-data.js from the scraped 999.md dump (cars_full.json)."""
import json, re, sys, os

SRC = sys.argv[1] if len(sys.argv) > 1 else os.path.join(os.path.dirname(__file__), '..', 'data', 'cars_full.json')
OUT = os.path.join(os.path.dirname(__file__), '..', 'js', 'cars-data.js')

cars = json.load(open(SRC))

def num(s):
    m = re.search(r'[\d.]+', (s or '').replace(' ', ''))
    return m.group(0) if m else None

out = []
for c in cars:
    f = c['features']
    desc = (c['description'] or '').replace('\r', '')
    equip, prose = [], []
    for line in desc.split('\n'):
        s = line.strip()
        # payment-methods boilerplate tail: same on every listing, not equipment
        if re.match(r'MODALIT', s, re.I):
            break
        if s.startswith('-'):
            item = s.lstrip('-').strip(' \t')
            if item:
                equip.append(item)
        elif s:
            prose.append(s)
    power = f.get('Putere')
    out.append({
        'id': c['id'],
        'make': f.get('Marcă', ''),
        'model': f.get('Model', ''),
        'name': (f.get('Marcă', '') + ' ' + f.get('Model', '')).strip() or c['listTitle'],
        'gen': f.get('Generație', ''),
        'year': c['year'] or int(f.get('An de fabricație', 0) or 0),
        'price': c['price']['value'],
        'km': c['mileage'] if c['mileage'] is not None else 0,
        'power': int(num(power)) if power and num(power) else None,
        'engine': f.get('Motor', ''),
        'fuel': f.get('Tip combustibil', '') or c.get('fuel') or '',
        'box': f.get('Cutie de viteze', '') or c.get('transmission') or '',
        'drive': f.get('Tip tracțiune', '') or c.get('drive') or '',
        'body': f.get('Tip caroserie', ''),
        'seats': f.get('Număr de locuri', ''),
        'doors': f.get('Număr uși', ''),
        'wheel': f.get('Volan', ''),
        'vin': f.get('VIN-cod', ''),
        'reg': f.get('Înmatriculare', ''),
        'origin': f.get('Țara de origine', ''),
        'avail': f.get('Disponibilitate', ''),
        'prose': '\n'.join(prose),
        'equip': equip,
        'images': c['images'],
        'url': 'https://999.md/ro/' + c['id'],
    })

banner = '// Generated by tools/build_data.py from 999.md PEAKAUTO stock. Do not edit by hand.\n'
with open(OUT, 'w') as fp:
    fp.write(banner)
    fp.write('window.PK_CARS = ')
    json.dump(out, fp, ensure_ascii=False, separators=(',', ':'))
    fp.write(';\n')

print('wrote', OUT, '-', len(out), 'cars,', sum(len(c["images"]) for c in cars), 'images')
